name: integration

on: pull_request


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Checkout sentry repository
        uses: actions/checkout@v3
        with:
          repository: getsentry/sentry
          path: sentry

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Setup Dependencies
        run: yarn install --frozen-lockfile

        # We add the package instead of linking here because we need to make
        # sure all dependencies are synced as well, which link will not do.
      - name: Install sentry dependencies
        run: |
          cd sentry
          yarn install --frozen-lockfile
          yarn add -D ../packages/eslint-config-sentry-app

      - name: Run lint in sentry
        env:
          SENTRY_ESLINT_RELAXED: 1
        run: |
          cd sentry
          yarn lint:prettier && yarn lint:js && yarn lint:css
